# Site settings
title: NHS Hack Day
name: NHS Hack Day | Geeks who love the NHS
email: hello@openhealthcare.org.uk
description: > # this means to ignore newlines until "baseurl:"
  Making NHS IT better
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nhshackday.com" # the base hostname & protocol for your site
twitter_username: NHSHackDay
markdown: kramdown
future: true
sass:
  sourceMap: true
  style: compressed
  sass_dir: _sass
